export const siteConfig = {
  name: "AGNXI",
  tagline: "Agent Skills Directory",
  description: "Directory of SKILL.md skills for coding assistants. Filter by tool, category, stars, and recent updates.",
  url: "https://agnxi.com",
  ogImage: "https://agnxi.com/og.png",
  twitterHandle: "@agnxi",
  links: {
    github: "https://github.com/doanbactam/kk",
    twitter: "https://x.com/agnxi",
  },
  keywords: [
    "agent skills",
    "SKILL.md",
    "Claude Code skills",
    "amp code skills",
    "cursor skills",
    "antigravity skills",
    "github copilot skills",
    "openai codex skills",
    "openai codex cli skills",
    "windsurf skills",
    "ai coding tools",
    "developer tools",
  ],
}
